CREATE OR REPLACE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE TABLE RETAIL_SALES_RAW (
    ORDER_ID STRING,
    DATE DATE,
    CUSTOMER_ID STRING,
    PRODUCT_CATEGORY STRING,
    PRODUCT_NAME STRING,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER,
    TOTAL_AMOUNT NUMBER,
    REGION STRING
);


CREATE OR REPLACE TABLE RETAIL_SALES_CLEANED AS
SELECT
    ORDER_ID,
    TO_DATE(DATE) AS ORDER_DATE,
    CUSTOMER_ID,
    INITCAP(PRODUCT_CATEGORY) AS PRODUCT_CATEGORY,
    INITCAP(PRODUCT_NAME) AS PRODUCT_NAME,
    QUANTITY,
    UNIT_PRICE,
    QUANTITY * UNIT_PRICE AS TOTAL_SALE_AMOUNT,
    UPPER(REGION) AS REGION
FROM RETAIL_SALES_RAW
WHERE ORDER_ID IS NOT NULL
  AND QUANTITY > 0
  AND UNIT_PRICE > 0;


CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT DISTINCT
    PRODUCT_CATEGORY,
    PRODUCT_NAME
FROM RETAIL_SALES_CLEANED;


CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT DISTINCT
    CUSTOMER_ID
FROM RETAIL_SALES_CLEANED;


CREATE OR REPLACE TABLE DIM_REGION AS
SELECT DISTINCT
    REGION
FROM RETAIL_SALES_CLEANED;


CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    REGION,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_SALE_AMOUNT
FROM RETAIL_SALES_CLEANED;


CREATE OR REPLACE VIEW V_SALES_BY_CATEGORY AS
SELECT
    PRODUCT_CATEGORY,
    SUM(TOTAL_SALE_AMOUNT) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM FACT_SALES
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTAL_SALES DESC;


CREATE OR REPLACE VIEW V_SALES_BY_REGION AS
SELECT
    REGION,
    SUM(TOTAL_SALE_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;


CREATE OR REPLACE VIEW V_MONTHLY_SALES AS
SELECT
    DATE_TRUNC('MONTH', ORDER_DATE) AS MONTH,
    SUM(TOTAL_SALE_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY MONTH
ORDER BY MONTH;